zefitret/zefitret/Controllers/SpeciesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using zefitret.Models;
using System.Net;
using System.IO;

namespace zefitret.Controllers
{
    public class SpeciesController : Controller
    {
        zefitretuserdbEntities db = new zefitretuserdbEntities();

       
        public ActionResult Index(string Viewer , string SearchValue)
        {
            var model = from s in db.SpeciesDataTables
                        select new SpeciesModelClass
                        {
                            MId = s.SId,
                            MCategory = s.Category,
                            MSName = s.SName,
                            MLocalName = s.LocalName,
                            MCommonName = s.CommonName,
                            MDescription = s.Description,
                            MMainPic = s.MainPic,
                            MSecPic = s.SecPic,
                            MThirdPic = s.ThirdPic,
                            MFourthPic = s.FourthPic,
                            MPicTakenBy = s.PicTakenBy,
                            MContentBy = s.ContentBy,
                            MEditedBy = s.EditedBy,
                        };


            var Query = from q in model
                        select q;

            if (SearchValue != null)
            {
                return View(model = model.Where(q => q.MSName.Contains(SearchValue)|| 
                q.MLocalName.Contains(SearchValue) || q.MCommonName.Contains(SearchValue)|| q.MCategory.Contains(SearchValue)||
                q.MPicTakenBy.Contains(SearchValue) || q.MContentBy.Contains(SearchValue) ||
                q.MDescription.Contains(SearchValue) || q.MEditedBy.Contains(SearchValue))); 
               
            }

            ViewBag.Amphibians = string.IsNullOrEmpty(Viewer) ? "Amphibians" : "Amphibians";
            ViewBag.Reptiles = string.IsNullOrEmpty(Viewer) ? "Reptiles" : "Reptiles";
            ViewBag.birds = string.IsNullOrEmpty(Viewer) ? "birds" : "birds";
            ViewBag.bugs = string.IsNullOrEmpty(Viewer) ? "invertebrates" : "invertebrates";
            ViewBag.mammals = string.IsNullOrEmpty(Viewer) ? "Mammals" : "Mammals";
            ViewBag.Flowers = string.IsNullOrEmpty(Viewer) ? "flora" : "flora";
            switch (Viewer)
            {
                case "Amphibians":
                    Query = Query.Where(q => q.MCategory == "Amphibians");

                    ViewBag.Category = "Amphibians";
                    break;

                case "Reptiles":
                    Query = Query.Where(q => q.MCategory == "reptiles");
                    ViewBag.Category = "reptiles";
                    break;
                case "birds":
                    Query = Query.Where(q => q.MCategory == "birds");
                    ViewBag.Category = "birds";
                    break;
                case "invertebrates":
                    Query = Query.Where(q => q.MCategory == "invertebrates");
                    ViewBag.Category = "invertebrates";
                    break;
                case "Mammals":
                    Query = Query.Where(q => q.MCategory == "Mammals");
                    ViewBag.Category = "Mammals";
                    break;
                case "flora":
                    Query = Query.Where(q => q.MCategory == "flora");
                    ViewBag.Category = "flora";
                    break;
                default:
                    Query = Query.Where(q => q.MCategory == "Amphibians");
                    ViewBag.Category = "Amphibians";
                    break;
            }

            
            
            return View(Query);
            
        }


        public ActionResult AddnewSpecies()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("LogIn", "Account");
            }

            return View();
        }



       

        [HttpPost, ActionName("AddnewSpecies")]
        public ActionResult SaveDataAdded([Bind(Include = "SId,Category,SName,LocalName,CommonName,Description,PicTakenBy,ContentBy,EditedBy")]SpeciesDataTable ARow, HttpPostedFileBase file, HttpPostedFileBase file2, HttpPostedFileBase file3, HttpPostedFileBase file4)
        {

            if (ModelState.IsValid)
            {

                if (file != null && file.ContentLength > 0)
                {
                    using (var Bnryreader = new System.IO.BinaryReader(file.InputStream))
                    {
                        ARow.MainPic = Bnryreader.ReadBytes(file.ContentLength);
                    }

                }

                if (file2 != null && file2.ContentLength > 0)
                {
                    using (var reader = new System.IO.BinaryReader(file2.InputStream))
                    {
                        ARow.SecPic = reader.ReadBytes(file2.ContentLength);
                    }

                }
                if (file3 != null && file3.ContentLength > 0)
                {
                    using (var reader = new System.IO.BinaryReader(file3.InputStream))
                    {
                        ARow.ThirdPic = reader.ReadBytes(file3.ContentLength);
                    }

                }
                if (file4 != null && file4.ContentLength > 0)
                {
                    using (var reader = new System.IO.BinaryReader(file4.InputStream))
                    {
                        ARow.FourthPic = reader.ReadBytes(file4.ContentLength);
                    }

                }


                db.SpeciesDataTables.Add(ARow);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ARow);

        }



        // EditSpecies Get
        public ActionResult EditSpecies(int EId)  // this EId is coming from Index EditSpecies link
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("LogIn", "Account");
            }



            var e = db.SpeciesDataTables.Find(EId);
            var vm = new SpeciesModelClass() { MId = EId, MSName = e.SName };
            vm.MCategory = e.Category;
            vm.MLocalName = e.LocalName;
            vm.MCommonName = e.CommonName;
            vm.MDescription = e.Description;
            vm.MPicTakenBy = e.PicTakenBy;
            vm.MContentBy = e.ContentBy;
            vm.MEditedBy = e.EditedBy;

            if (e.MainPic != null)
            {
                vm.MainSrc = $"data:image/jpg;base64,{Convert.ToBase64String(e.MainPic)}";
            }
            if (e.SecPic != null)
            {
                vm.SecondSrc = $"data:image/jpg;base64,{Convert.ToBase64String(e.SecPic)}";
            }
            if (e.ThirdPic != null)
            {
                vm.ThirdSrc = $"data:image/jpg;base64,{Convert.ToBase64String(e.ThirdPic)}";
            }
            if (e.FourthPic != null)
            {
                vm.FourthSrc = $"data:image/jpg;base64,{Convert.ToBase64String(e.FourthPic)}";
            }
            return View(vm);


        }

        [HttpPost]

        public ActionResult EditSpecies(SpeciesModelClass model, int MId)
        {
            var e = db.SpeciesDataTables.Find(MId);
            e.Category = model.MCategory;
            e.SName = model.MSName;
            e.LocalName = model.MLocalName;
            e.CommonName = model.MCommonName;
            e.Description = model.MDescription;
            e.PicTakenBy = model.MPicTakenBy;
            e.ContentBy = model.MContentBy;
            e.EditedBy = model.MEditedBy;

            //Update the image properties only if it was send from the form
            if (model.MainImg != null)
            {
                e.MainPic = GetByteArrayFromImage(model.MainImg);
            }
            if (model.SecondImg != null)
            {
                e.SecPic = GetByteArrayFromImage(model.SecondImg);
            }
            if (model.ThirdImg != null)
            {
                e.ThirdPic = GetByteArrayFromImage(model.ThirdImg);
            }
            if (model.FourthImg != null)
            {
                e.FourthPic = GetByteArrayFromImage(model.FourthImg);
            }

            db.SaveChanges();
            return RedirectToAction("Index");

        }
        private byte[] GetByteArrayFromImage(HttpPostedFileBase file)
        {
            if (file == null)
                return null;
            var target = new MemoryStream();
            file.InputStream.CopyTo(target);
            return target.ToArray();
        }




        public ActionResult SpeciesDetail(int? DetailId)
        {
            if (DetailId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }
            SpeciesDataTable DetailTable = db.SpeciesDataTables.Find(DetailId);
            if (DetailTable == null)
            {
                return HttpNotFound();
            }
            return View(DetailTable);

        }




        // delete get Request
        public ActionResult DeleteSpecies(int? DeleteId)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("LogIn", "Account");
            }


            if (DeleteId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            SpeciesDataTable SMCForDelete = db.SpeciesDataTables.Find(DeleteId);
            if (SMCForDelete == null)
            {
                return HttpNotFound();
            }
            return View(SMCForDelete);

zefitret/zefitret/Views/Species/AddnewSpecies.cshtml
@model zefitret.Models.SpeciesDataTable

@{
    ViewBag.Title = "Add New Species";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("AddNewSpecies", "Species", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="col-sm-12" style="padding-bottom:1em;">
                    <label for="Category" class="control-label">Category</label>
                    @Html.DropDownListFor(x => x.Category, new[] {
                new SelectListItem() {Text = "Amphibians",},
                new SelectListItem() {Text = "reptiles",},
                new SelectListItem() {Text = "birds",},
                new SelectListItem() {Text = "invertebrates",},
                new SelectListItem() {Text = "Mammals",},
                new SelectListItem() {Text = "flora",},
                    }, "Choose an option", new { @class = "form-control" })

                </div>

            </div>
            <div class="col-sm-6">

                <div class="col-sm-12" style="padding-bottom:1em;">
                    <label for="SName" class="control-label">Scientific Name</label>
                    @Html.EditorFor(model => model.SName, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="col-sm-12" style="padding-bottom:1em;">
                    <label for="LocalName" class="control-label">Local Name</label>


                    @Html.EditorFor(model => model.LocalName, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="col-sm-12" style="padding-bottom:1em;">
                    <label for="CommonName" class="control-label">Common Name</label>


                    @Html.EditorFor(model => model.CommonName, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="col-sm-6">
                <div class="col-sm-12" style="padding-bottom:1em;">
                    <label for="PicTakenBy" class="control-label">Pictures By</label>
                    @Html.EditorFor(model => model.PicTakenBy, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="col-sm-12" style="padding-bottom:1em;">
                    <label for="ContentBy" class="control-label">Content By</label>
                    @Html.EditorFor(model => model.ContentBy, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="col-sm-12" style="padding-bottom:1em;">
                    <label for="EditedBy" class="control-label">Edited By</label>
                    @Html.EditorFor(model => model.EditedBy, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="col-sm-12" style="padding-bottom:1em;">

                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <label for="Description" class="control-label">Description</label>

                <div class="col-sm-12">
                   <p>
                   @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", style = "width: 100% !Important; height: 100% !Important;" } }) 
                    </p> 
                </div>
            </div>

            <div class="col-sm-4">
                <img src="~/Content/template/image-logo/flora.png" style="width:50px;height:50px;" />
                <div class="form-group">
                    <input type="file" id="ARow" name="file" />
                </div>
                <img src="~/Content/template/image-logo/flora.png" style="width:50px;height:50px;" />
                <div class="form-group">
                    <input type="file" id="ARow" name="file2" />
                </div>
            </div>

            <div class="col-sm-4">
                <img src="~/Content/template/image-logo/flora.png" style="width:50px;height:50px;" />
                <div class="form-group">
                    <input type="file" id="ARow" name="file3" />
                </div>
                <img src="~/Content/template/image-logo/flora.png" style="width:50px;height:50px;" />
                <div class="form-group">
                    <input type="file" id="ARow" name="file4" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="offset-5" style="margin-top:15px;">
                <input type="submit" value="Publish" class="btn btn-primary" />  @Html.ActionLink("Cancel", "Index", "Species", new object { }, new { @class = "btn btn-secondary" })
            </div>
        </div>
    </div>
}




zefitret/zefitret/Views/Species/DeleteSpecies.cshtml
@model zefitret.Models.SpeciesDataTable

@{
    ViewBag.Title = "DeleteSpecies";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h3 style="text-align:center;">Are you sure you want to delete this?</h3>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="col-sm-12" style="padding-bottom:1em;">
                <div><label for="Category" class="control-label">Category</label></div>

                <p id="rectangle">
                    @Html.DisplayFor(model => model.Category)
                </p>


            </div>

        </div>
        <div class="col-sm-6">
            <div class="col-sm-12" @*style="padding-bottom:1em;*@ ">
                <label for="SName" class="control-label">Scientific Name</label>
                <p id="rectangle-col-6">
                    @Html.DisplayFor(model => model.SName)
                </p>

            </div>

            <div class="col-sm-12" @*style="padding-bottom:1em;"*@>
                <label for="LocalName" class="control-label">Local Name</label>
                <p id="rectangle-col-6">@Html.DisplayFor(model => model.LocalName)</p>
            </div>

            <div class="col-sm-12" @*style="padding-bottom:1em;"*@>
                <label for="CommonName" class="control-label">Common Name</label>
                <p id="rectangle-col-6">@Html.DisplayFor(model => model.CommonName)</p>
            </div>
        </div>


        <div class="col-sm-6">

            <div class="col-sm-12" @*style="padding-bottom:1em;"*@>
                <label for="PicTakenBy" class="control-label">Pictures By</label>
                <p id="rectangle-col-6"> @Html.DisplayFor(model => model.PicTakenBy)</p>
            </div>



            <div class="col-sm-12" @*style="padding-bottom:1em;"*@>
                <label for="ContentBy" class="control-label">Content By</label>
                <p id="rectangle-col-6"> @Html.DisplayFor(model => model.ContentBy)</p>
            </div>



            <div class="col-sm-12" @*style="padding-bottom:1em;"*@>
                <label for="EditedBy" class="control-label">Edited By</label>
                <p id="rectangle-col-6">@Html.DisplayFor(model => model.EditedBy)</p>
            </div>

        </div>
    </div>
</div>

@*//----- for picture view and edit ------*@

<div class="container">
    <div class="row" @*style="background-color:blueviolet;"*@>
        <div class="col-sm-6" @*style="background-color:#ffd800;"*@>
            <div class="form-group">

                <div class="col-md-12">
                    <label for="Description" class="control-label">Description</label>
                    <p id="rectangle-description">
                        @Html.DisplayFor(model => model.Description)
                    </p>

                </div>
            </div>
        </div>

        <div class="col-sm-6" @*style="background-color:#808080;"*@>

            <div class="col-md-12">

                @if (Model.MainPic != null)
            {
                var base64 = Convert.ToBase64String(Model.MainPic);
                var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                    <img src='@imgsrc' id="picForDelete" class="img-responsive" />
                }
                else
                {
                    <img src="~/Content/template/image-logo/flora.png" id="picForDelete" />
                }


                @if (Model.SecPic != null)
            {
                var base64 = Convert.ToBase64String(Model.SecPic);
                var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                    <img src='@imgsrc' id="picForDelete" class="img-responsive" />
                }
                else
                {
                    <img src="~/Content/template/image-logo/flora.png" id="picForDelete" />
                }

            </div>
            <div class="col-md-12">

                @if (Model.ThirdPic != null)
            {
                var base64 = Convert.ToBase64String(Model.ThirdPic);
                var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                    <img src='@imgsrc' id="picForDelete" class="img-responsive" />
                }
                else
                {
                    <img src="~/Content/template/image-logo/flora.png" id="picForDelete" />
                }

                @if (Model.FourthPic != null)
            {
                var base64 = Convert.ToBase64String(Model.FourthPic);
                var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                    <img src='@imgsrc' id="picForDelete" class="img-responsive" />
                }
                else
                {
                    <img src="~/Content/template/image-logo/flora.png" id="picForDelete" />
                }


            </div>

        </div>

    </div>


</div>



<div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="offset-5" style="margin-top:15px;">
            <input type="submit" value="Delete" class="btn btn-danger" />
            @Html.ActionLink("Cancel", "Index", "Species", new object { }, new { @class = "btn btn-secondary", @style = "padding-left:20px !Important;" })

        </div>

    }
</div>

zefitret/zefitret/Views/Species/EditSpecies.cshtml

@model zefitret.Models.SpeciesModelClass

@{
    ViewBag.Title = "EditSpecies";
    Layout = "~/Views/Shared/_Layout.cshtml";
}






@using (Html.BeginForm("EditSpecies", "Species", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="row">
            @Html.HiddenFor(a => a.MId)

            <div class="col-sm-12">
                @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@

                <div class="col-sm-12" style="padding-bottom:1em;">
                    <label for="MCategory" class="control-label">Category</label>
                    @Html.DropDownListFor(x => x.MCategory, new[] {
                    new SelectListItem() {Text = "Amphibians",},
                    new SelectListItem() {Text = "reptiles",},
                    new SelectListItem() {Text = "birds",},
                    new SelectListItem() {Text = "invertebrates",},
                    new SelectListItem() {Text = "Mammals",},
                    new SelectListItem() {Text = "flora",},
                        }, "Choose an option", new { @class = "form-control" })


                </div>

            </div>
            <div class="col-sm-6">
                <div class="col-sm-12" style="padding-bottom:1em;">
                    <label for="MSName" class="control-label">Scientific Name</label>
                    @Html.EditorFor(a => a.MSName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(a => a.MSName, "", new { @class = "text-danger" })
                </div>

                <div class="col-sm-12" style="padding-bottom:1em;">
                    <label for="MLocalName" class="control-label">Local Name</label>
                    @Html.EditorFor(a => a.MLocalName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(a => a.MLocalName, "", new { @class = "text-danger" })
                </div>

                <div class="col-sm-12" style="padding-bottom:1em;">
                    <label for="MCommonName" class="control-label">Common Name</label>
                    @Html.EditorFor(a => a.MCommonName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(a => a.MCommonName, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="col-sm-6">

                <div class="col-sm-12" style="padding-bottom:1em;">
                    <label for="MPicTakenBy" class="control-label">Pictures By</label>
                    @Html.EditorFor(a => a.MPicTakenBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(a => a.MPicTakenBy, "", new { @class = "text-danger" })
                </div>


                <label for="MContentBy" class="control-label">Content By</label>
                <div class="col-sm-12" style="padding-bottom:1em;">
                    @Html.EditorFor(a => a.MContentBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(a => a.MContentBy, "", new { @class = "text-danger" })
                </div>


                <label for="MEditedBy" class="control-label">Edited By</label>
                <div class="col-sm-12" style="padding-bottom:1em;">
                    @Html.EditorFor(a => a.MEditedBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(a => a.MEditedBy, "", new { @class = "text-danger" })
                </div>

            </div>
        </div>
    </div>

    //----- for picture view and edit ------

    <div class="container">
        <div class="row">
            <div class="offset-1 col-sm-10 col-sm-offset-1">
                <div class="col-md-12">
                    <label for="Description" class="control-label">Description</label>

                    @Html.TextAreaFor(a => a.MDescription, new { htmlAttributes = new { @class = "form-control", @id = "rectangle-description" } })
                    @Html.ValidationMessageFor(a => a.MDescription, "", new { @class = "text-danger" })
                </div>

            </div>

        </div>
        <div class="row">


            <div class="col-sm-3">

                <div class="col-md-12 ">
                    @if (!string.IsNullOrEmpty(Model.MainSrc))
                {
                        <img src='@Model.MainSrc' id="picForEdit" class="img-responsive img-thumbnail" />
                    }
                    else
                    {
                        <img src="~/Content/template/image-logo/flora.png" id="picForEdit" class="img-responsive img-rounded" />
                    }

                </div>
                <div class="col-md-12">

                    <p><input type="file" name="MainImg" /></p>

                </div>

            </div>
            <div class="col-sm-3">

                <div class="col-md-12">
                    @if (!string.IsNullOrEmpty(Model.SecondSrc))
                {
                        <img src='@Model.SecondSrc' id="picForEdit" class="img-responsive img-thumbnail" />
                    }
                    else
                    {
                        <img src="~/Content/template/image-logo/flora.png" id="picForEdit" class="img-responsive img-rounded" />
                    }


                </div>
                <div class="col-md-12">

                    <input type="file" name="SecondImg" />

                </div>

            </div>
            <div class="col-sm-3">
                <div class="col-md-12">
                    @if (!string.IsNullOrEmpty(Model.ThirdSrc))
                {
                        <img src='@Model.ThirdSrc' id="picForEdit" class="img-responsive img-thumbnail" />
                    }
                    else
                    {
                        <img src="~/Content/template/image-logo/flora.png" id="picForEdit" class="img-responsive img-rounded" />
                    }


                </div>
                <div class="col-md-12">

                    <input type="file" name="ThirdImg" />

                </div>


            </div>
            <div class="col-sm-3">
                <div class="col-md-12">
                    @if (!string.IsNullOrEmpty(Model.FourthSrc))
                {
                        <img src='@Model.FourthSrc' id="picForEdit" class="img-responsive img-thumbnail" />
                    }
                    else
                    {
                        <img src="~/Content/template/image-logo/flora.png" id="picForEdit" class="img-responsive img-rounded" />
                    }


                </div>
                <div class="col-md-12">

                    <input type="file" name="FourthImg" />

                </div>


            </div>
        </div>


    </div>











    <div class="form-group">
        <div class="offset-6" style="margin-top:15px;align-items:center;">
            <button type="submit" class="btn btn-success">Save</button>
            @Html.ActionLink("Cancel", "Index", "Species", new object { }, new { @class = "btn btn-secondary", @style = "padding-left:20px !Important;" })

        </div>
    </div>





}






zefitret/zefitret/Views/Species/Index.cshtml
@model IEnumerable<zefitret.Models.SpeciesModelClass>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="row">
        @foreach (var item in Model)
    {
        <div class="col-lg-6 col-md-6 portfolio-item">
            <a href="@Url.Action("SpeciesDetail", new { DetailId = item.MId })" class="link-col">

                @if (item.MMainPic != null)
                {
                    var base64 = Convert.ToBase64String(item.MMainPic);
                    var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                    <img src='@imgsrc' class="img-responsive" id="index-image" />
                }
                else if (item.MMainPic == null)
                {
                    <img src="~/Content/template/image-logo/flora.png" />
                }

                <h3 class="link-col" id="div-title">
                    @Html.DisplayFor(model => item.MSName)
                </h3>
            </a>
            <p id="div-title">Content about this species is comming soon</p>




            @Html.ActionLink("Edit", "EditSpecies", new { EId = item.MId }, new { @class = "btn btn-primary", @id = "div-title" })
            @Html.ActionLink("Delete", "DeleteSpecies", new { DeleteId = item.MId }, new { @class = "btn btn-danger" })

        </div>

    }
</div>


